/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MedicationOrderSystem.Forms;


import MedicationOrderSystem.Forms.UserGUI;
import MedicationOrderSystem.Forms.RegistrationGUI;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import javax.swing.JTextField;
/**
 *
 * @author OENAL
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public LoginGUI() {
        
        initComponents();
        addPlaceholderStyle(tf_Username);
        addPlaceholderStyle(tf_Password);
    }
    
    public void addPlaceholderStyle(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.gray);
    }
    
    public void removePlaceholderStyle(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN|Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Title = new javax.swing.JLabel();
        lbl_Icon = new javax.swing.JLabel();
        lbl_IconPassword = new javax.swing.JLabel();
        tf_Username = new javax.swing.JTextField();
        lbl_IconUser = new javax.swing.JLabel();
        tf_Password = new javax.swing.JPasswordField();
        btn_Register = new javax.swing.JButton();
        lbl_frame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MOS System");
        setMaximumSize(new java.awt.Dimension(347, 650));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Title.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbl_Title.setForeground(new java.awt.Color(0, 204, 204));
        lbl_Title.setText("MOS System");
        lbl_Title.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(lbl_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        lbl_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MOSLogo.png"))); // NOI18N
        getContentPane().add(lbl_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        lbl_IconPassword.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_IconPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/password.png"))); // NOI18N
        getContentPane().add(lbl_IconPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        tf_Username.setText("Username");
        tf_Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_UsernameFocusLost(evt);
            }
        });
        tf_Username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_UsernameKeyPressed(evt);
            }
        });
        getContentPane().add(tf_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 219, 37));

        lbl_IconUser.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_IconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/username.png"))); // NOI18N
        getContentPane().add(lbl_IconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        tf_Password.setText("Password");
        tf_Password.setEchoChar('\u0000');
        tf_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_PasswordFocusLost(evt);
            }
        });
        tf_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_PasswordKeyPressed(evt);
            }
        });
        getContentPane().add(tf_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 219, 37));

        btn_Register.setText("Register (new account)");
        btn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, 160, 30));

        btn_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login.png"))); // NOI18N
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 70, 70));

        lbl_frame.setToolTipText("");
        lbl_frame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(lbl_frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 350, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegisterActionPerformed
        // TODO add your handling code here:
        new RegistrationGUI().setVisible(true);
    }//GEN-LAST:event_btn_RegisterActionPerformed

    private void tf_UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_UsernameFocusGained
        // TODO add your handling code here:
        if(tf_Username.getText().equals("Username")){
            tf_Username.setText(null);
            tf_Username.requestFocus();
            removePlaceholderStyle(tf_Username);
        }
    }//GEN-LAST:event_tf_UsernameFocusGained

    private void tf_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_PasswordFocusGained
        // TODO add your handling code here:
        if(tf_Password.getText().equals("Password")){
            tf_Password.setText(null);
            tf_Password.requestFocus();
            tf_Password.setEchoChar('\u2022');
            removePlaceholderStyle(tf_Password);
        }
    }//GEN-LAST:event_tf_PasswordFocusGained

    private void tf_UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_UsernameFocusLost
        // TODO add your handling code here:
        if(tf_Username.getText().length()==0){
            addPlaceholderStyle(tf_Username);
            tf_Username.setText("Username");
        }
    }//GEN-LAST:event_tf_UsernameFocusLost

    private void tf_PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_PasswordFocusLost
        // TODO add your handling code here:
        if(tf_Password.getText().length()==0){
            addPlaceholderStyle(tf_Password);
            tf_Password.setText("Password");
            tf_Password.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_tf_PasswordFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void tf_PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_PasswordKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        
        if(key == KeyEvent.VK_ENTER){
            btn_Login.doClick();
        }
    }//GEN-LAST:event_tf_PasswordKeyPressed

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        // TODO add your handling code here:
        new UserGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_LoginActionPerformed

    private void tf_UsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_UsernameKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        
        if(key == KeyEvent.VK_ENTER){
            btn_Login.doClick();
        }
    }//GEN-LAST:event_tf_UsernameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final javax.swing.JButton btn_Login = new javax.swing.JButton();
    private javax.swing.JButton btn_Register;
    private javax.swing.JLabel lbl_Icon;
    private javax.swing.JLabel lbl_IconPassword;
    private javax.swing.JLabel lbl_IconUser;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JLabel lbl_frame;
    private javax.swing.JPasswordField tf_Password;
    private javax.swing.JTextField tf_Username;
    // End of variables declaration//GEN-END:variables

}
