/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MedicationOrderSystem.Forms;
import MedicationOrderSystem.Handler.*;
import MedicationOrderSystem.Classes.*;

import java.awt.Color;
import java.awt.Font;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author OENAL
 */
public class RegistrationGUI extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public RegistrationGUI() {
        initComponents();
        addPlaceholderStyle(tf_Username);
        addPlaceholderStyle(tf_FirstName);
        addPlaceholderStyle(tf_Mail);
        addPlaceholderStyle(tf_RepeatMail);
        addPlaceholderStyle(tf_Password);
        addPlaceholderStyle(tf_RepeatPassword);
        addPlaceholderStyle(tf_ZIP);
        addPlaceholderStyle(tf_City);
        addPlaceholderStyle(tf_StreetHouse);
        addPlaceholderStyle(tf_PhoneNumber);
        addPlaceholderStyle(jcb_Gender);
    }
    
    public void addPlaceholderStyle(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.gray);
    }
    
    public void addPlaceholderStyle(JComboBox comboBox){
        Font font = comboBox.getFont();
        font = font.deriveFont(Font.ITALIC);
        comboBox.setFont(font);
        comboBox.setForeground(Color.gray);
    }
    
    public void removePlaceholderStyle(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN|Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }
    
    public void removePlaceholderStyle(JComboBox comboBox){
        Font font = comboBox.getFont();
        font = font.deriveFont(Font.PLAIN|Font.BOLD);
        comboBox.setFont(font);
        comboBox.setForeground(Color.black);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        lbl_Icon = new javax.swing.JLabel();
        lbl_Username = new javax.swing.JLabel();
        lbl_FirstName = new javax.swing.JLabel();
        lbl_Mail = new javax.swing.JLabel();
        lbl_RepeatMail = new javax.swing.JLabel();
        lbl_Password = new javax.swing.JLabel();
        lbl_RepeatPassword = new javax.swing.JLabel();
        lbl_Birthday = new javax.swing.JLabel();
        tf_FirstName = new javax.swing.JTextField();
        tf_Mail = new javax.swing.JTextField();
        tf_RepeatMail = new javax.swing.JTextField();
        tf_Username = new javax.swing.JTextField();
        tf_Password = new javax.swing.JTextField();
        tf_RepeatPassword = new javax.swing.JTextField();
        jdc_Birthday = new com.toedter.calendar.JDateChooser();
        jcb_AcceptPolicy = new javax.swing.JCheckBox();
        btn_Register = new javax.swing.JButton();
        lbl_Gender = new javax.swing.JLabel();
        jcb_Gender = new javax.swing.JComboBox<>();
        tf_PhoneNumber = new javax.swing.JTextField();
        lbl_PhoneNumber = new javax.swing.JLabel();
        lbl_ZIP = new javax.swing.JLabel();
        lbl_City = new javax.swing.JLabel();
        tf_ZIP = new javax.swing.JTextField();
        tf_City = new javax.swing.JTextField();
        tf_LastName = new javax.swing.JTextField();
        lbl_LastName = new javax.swing.JLabel();
        lbl_StreetHouse = new javax.swing.JLabel();
        tf_StreetHouse = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registration");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        lbl_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MOSLogo.png"))); // NOI18N

        lbl_Username.setText("Username");

        lbl_FirstName.setText("First Name");

        lbl_Mail.setText("Mail");

        lbl_RepeatMail.setText("Repeat Mail");

        lbl_Password.setText("Password");

        lbl_RepeatPassword.setText("Repeat Password");

        lbl_Birthday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Birthday.setText("Birthday");

        tf_FirstName.setText("First Name");
        tf_FirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_FirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_FirstNameFocusLost(evt);
            }
        });

        tf_Mail.setText("Mail");
        tf_Mail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_MailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_MailFocusLost(evt);
            }
        });

        tf_RepeatMail.setText("Repeat Mail");
        tf_RepeatMail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_RepeatMailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_RepeatMailFocusLost(evt);
            }
        });

        tf_Username.setText("Username");
        tf_Username.setToolTipText("");
        tf_Username.setInheritsPopupMenu(true);
        tf_Username.setName(""); // NOI18N
        tf_Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_UsernameFocusLost(evt);
            }
        });

        tf_Password.setText("Password");
        tf_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_PasswordFocusLost(evt);
            }
        });

        tf_RepeatPassword.setText("Repeat Password");
        tf_RepeatPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_RepeatPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_RepeatPasswordFocusLost(evt);
            }
        });
        tf_RepeatPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_RepeatPasswordActionPerformed(evt);
            }
        });

        jcb_AcceptPolicy.setText("Agree to our privacy policy");
        jcb_AcceptPolicy.setToolTipText("");

        btn_Register.setText("Register");
        btn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegisterActionPerformed(evt);
            }
        });

        lbl_Gender.setText("Gender");

        jcb_Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender", "Male", "Female", "Divers" }));
        jcb_Gender.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcb_GenderFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jcb_GenderFocusLost(evt);
            }
        });
        jcb_Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_GenderActionPerformed(evt);
            }
        });

        tf_PhoneNumber.setText("Phone number");
        tf_PhoneNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_PhoneNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_PhoneNumberFocusLost(evt);
            }
        });

        lbl_PhoneNumber.setText("Phone Number");

        lbl_ZIP.setText("ZIP");

        lbl_City.setText("City");

        tf_ZIP.setText("ZIP");
        tf_ZIP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_ZIPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_ZIPFocusLost(evt);
            }
        });
        tf_ZIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ZIPActionPerformed(evt);
            }
        });

        tf_City.setText("City");
        tf_City.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_CityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_CityFocusLost(evt);
            }
        });
        tf_City.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_CityActionPerformed(evt);
            }
        });

        tf_LastName.setText("Last Name");
        tf_LastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_LastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_LastNameFocusLost(evt);
            }
        });
        tf_LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_LastNameActionPerformed(evt);
            }
        });

        lbl_LastName.setText("Last Name");

        lbl_StreetHouse.setText("Street, Housenumber");

        tf_StreetHouse.setText("Street, Housenumber");
        tf_StreetHouse.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_StreetHouseFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_StreetHouseFocusLost(evt);
            }
        });
        tf_StreetHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_StreetHouseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jcb_AcceptPolicy))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lbl_Icon)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_Username)
                        .addComponent(tf_Username, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(lbl_Mail)
                        .addComponent(lbl_Password)
                        .addComponent(tf_Password, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(tf_Mail))
                    .addComponent(lbl_LastName)
                    .addComponent(tf_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_Gender)
                        .addComponent(jcb_Gender, 0, 130, Short.MAX_VALUE)
                        .addComponent(lbl_ZIP)
                        .addComponent(tf_ZIP, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_FirstName)
                    .addComponent(lbl_RepeatMail)
                    .addComponent(lbl_RepeatPassword)
                    .addComponent(tf_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_RepeatMail, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_RepeatPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_StreetHouse)
                    .addComponent(tf_StreetHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_PhoneNumber)
                    .addComponent(lbl_City)
                    .addComponent(tf_City, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdc_Birthday, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(lbl_Birthday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_FirstName)
                            .addComponent(lbl_Username, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_RepeatMail)
                            .addComponent(lbl_Mail, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_RepeatMail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_Mail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Password)
                            .addComponent(lbl_RepeatPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_RepeatPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_Icon))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_LastName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_StreetHouse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_StreetHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_ZIP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_ZIP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_Gender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_City)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_City, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_PhoneNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcb_AcceptPolicy, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(lbl_Birthday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdc_Birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btn_Register)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_RepeatPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_RepeatPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_RepeatPasswordActionPerformed

    private void jcb_GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_GenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_GenderActionPerformed

    
    private void tf_UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_UsernameFocusGained
        // TODO add your handling code here:
        if(tf_Username.getText().equals("Username")){
            tf_Username.setText(null);
            tf_Username.requestFocus();
            removePlaceholderStyle(tf_Username);
        }
    }//GEN-LAST:event_tf_UsernameFocusGained

    private void tf_FirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_FirstNameFocusGained
        // TODO add your handling code here:
        if(tf_FirstName.getText().equals("Firstname")){
            tf_FirstName.setText(null);
            tf_FirstName.requestFocus();
            removePlaceholderStyle(tf_FirstName);
        }
    }//GEN-LAST:event_tf_FirstNameFocusGained

    private void tf_MailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_MailFocusGained
        // TODO add your handling code here:
        if(tf_Mail.getText().equals("Mail")){
            tf_Mail.setText(null);
            tf_Mail.requestFocus();
            removePlaceholderStyle(tf_Mail);
        }
    }//GEN-LAST:event_tf_MailFocusGained

    private void tf_RepeatMailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_RepeatMailFocusGained
        // TODO add your handling code here:
        if(tf_RepeatMail.getText().equals("Lastname")){
            tf_RepeatMail.setText(null);
            tf_RepeatMail.requestFocus();
            removePlaceholderStyle(tf_RepeatMail);
        }
    }//GEN-LAST:event_tf_RepeatMailFocusGained

    private void tf_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_PasswordFocusGained
        // TODO add your handling code here:
        if(tf_Password.getText().equals("Password")){
            tf_Password.setText(null);
            tf_Password.requestFocus();
            removePlaceholderStyle(tf_Password);
        }
    }//GEN-LAST:event_tf_PasswordFocusGained

    private void tf_RepeatPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_RepeatPasswordFocusGained
        // TODO add your handling code here:
        if(tf_RepeatPassword.getText().equals("Street")){
            tf_RepeatPassword.setText(null);
            tf_RepeatPassword.requestFocus();
            removePlaceholderStyle(tf_RepeatPassword);
        }
    }//GEN-LAST:event_tf_RepeatPasswordFocusGained

    private void tf_PhoneNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_PhoneNumberFocusGained
        // TODO add your handling code here:
        if(tf_PhoneNumber.getText().equals("Phone number")){
            tf_PhoneNumber.setText(null);
            tf_PhoneNumber.requestFocus();
            removePlaceholderStyle(tf_PhoneNumber);
        }
    }//GEN-LAST:event_tf_PhoneNumberFocusGained

    private void tf_UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_UsernameFocusLost
        // TODO add your handling code here:
        if(tf_Username.getText().length()==0){
            addPlaceholderStyle(tf_Username);
            tf_Username.setText("Username");
        }
    }//GEN-LAST:event_tf_UsernameFocusLost

    private void tf_FirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_FirstNameFocusLost
        // TODO add your handling code here:
        if(tf_FirstName.getText().length()==0){
            addPlaceholderStyle(tf_FirstName);
            tf_FirstName.setText("Firstname");
        }
    }//GEN-LAST:event_tf_FirstNameFocusLost

    private void tf_MailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_MailFocusLost
        // TODO add your handling code here:
        if(tf_Mail.getText().length()==0){
            addPlaceholderStyle(tf_Mail);
            tf_Mail.setText("Mail");
        }
    }//GEN-LAST:event_tf_MailFocusLost

    private void tf_RepeatMailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_RepeatMailFocusLost
        // TODO add your handling code here:
        if(tf_RepeatMail.getText().length()==0){
            addPlaceholderStyle(tf_RepeatMail);
            tf_RepeatMail.setText("Lastname");
        }
    }//GEN-LAST:event_tf_RepeatMailFocusLost

    private void tf_PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_PasswordFocusLost
        // TODO add your handling code here:
        if(tf_Password.getText().length()==0){
            addPlaceholderStyle(tf_Password);
            tf_Password.setText("Password");
        }
    }//GEN-LAST:event_tf_PasswordFocusLost

    private void tf_RepeatPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_RepeatPasswordFocusLost
        // TODO add your handling code here:
        if(tf_RepeatPassword.getText().length()==0){
            addPlaceholderStyle(tf_RepeatPassword);
            tf_RepeatPassword.setText("Street");
        }
    }//GEN-LAST:event_tf_RepeatPasswordFocusLost

    private void tf_PhoneNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_PhoneNumberFocusLost
        // TODO add your handling code here:
        if(tf_PhoneNumber.getText().length()==0){
            addPlaceholderStyle(tf_PhoneNumber);
            tf_PhoneNumber.setText("Phone number");
        }
    }//GEN-LAST:event_tf_PhoneNumberFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void jcb_GenderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcb_GenderFocusGained
        // TODO add your handling code here:
        if(jcb_Gender.getItemAt(0).equals("Gender")){
            jcb_Gender.setName(null);
            jcb_Gender.removeItemAt(0);
            jcb_Gender.requestFocus();
            removePlaceholderStyle(jcb_Gender);
        }
    }//GEN-LAST:event_jcb_GenderFocusGained

    private void jcb_GenderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcb_GenderFocusLost
        // TODO add your handling code here:
        if(jcb_Gender.getItemAt(0).length()==0){
            addPlaceholderStyle(jcb_Gender);
            jcb_Gender.setName("Gender");
        }
    }//GEN-LAST:event_jcb_GenderFocusLost

    private void tf_ZIPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_ZIPFocusGained
        // TODO add your handling code here:
        if(tf_ZIP.getText().equals("ZIP")){
            tf_ZIP.setText(null);
            tf_ZIP.requestFocus();
            removePlaceholderStyle(tf_ZIP);
        }
    }//GEN-LAST:event_tf_ZIPFocusGained

    private void tf_ZIPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_ZIPFocusLost
        // TODO add your handling code here:
        if(tf_ZIP.getText().length()==0){
            addPlaceholderStyle(tf_ZIP);
            tf_ZIP.setText("ZIP");
        }
    }//GEN-LAST:event_tf_ZIPFocusLost

    private void tf_ZIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ZIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ZIPActionPerformed

    private void tf_CityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_CityFocusGained
        // TODO add your handling code here:
        if(tf_City.getText().equals("City")){
            tf_City.setText(null);
            tf_City.requestFocus();
            removePlaceholderStyle(tf_City);
        }
    }//GEN-LAST:event_tf_CityFocusGained

    private void tf_CityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_CityFocusLost
        // TODO add your handling code here:
        if(tf_City.getText().length()==0){
            addPlaceholderStyle(tf_City);
            tf_City.setText("City");
        }
    }//GEN-LAST:event_tf_CityFocusLost

    private void tf_CityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_CityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_CityActionPerformed

    private void btn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegisterActionPerformed
        Registration registerUser = new Registration(tf_Username.getText(), tf_FirstName.getText(), tf_LastName.getText(), tf_Password.getText(), tf_Mail.getText(), tf_RepeatPassword.getText(), tf_RepeatMail.getText());
        UserHandler userHandler = new UserHandler();
        EncryptionHandler encrypt = new EncryptionHandler();
        
        
        userHandler.tryToCreateNewUser(registerUser);
        userHandler.createNewUser(registerUser, rootPaneCheckingEnabled, rootPaneCheckingEnabled);
        encrypt.encryptPassword(tf_Password.getText(), tf_Username.getText());

    }//GEN-LAST:event_btn_RegisterActionPerformed

    private void tf_LastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_LastNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_LastNameFocusGained

    private void tf_LastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_LastNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_LastNameFocusLost

    private void tf_StreetHouseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_StreetHouseFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_StreetHouseFocusGained

    private void tf_StreetHouseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_StreetHouseFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_StreetHouseFocusLost

    private void tf_StreetHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_StreetHouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_StreetHouseActionPerformed

    private void tf_LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_LastNameActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Register;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JCheckBox jcb_AcceptPolicy;
    private javax.swing.JComboBox<String> jcb_Gender;
    private com.toedter.calendar.JDateChooser jdc_Birthday;
    private javax.swing.JLabel lbl_Birthday;
    private javax.swing.JLabel lbl_City;
    private javax.swing.JLabel lbl_FirstName;
    private javax.swing.JLabel lbl_Gender;
    private javax.swing.JLabel lbl_Icon;
    private javax.swing.JLabel lbl_LastName;
    private javax.swing.JLabel lbl_Mail;
    private javax.swing.JLabel lbl_Password;
    private javax.swing.JLabel lbl_PhoneNumber;
    private javax.swing.JLabel lbl_RepeatMail;
    private javax.swing.JLabel lbl_RepeatPassword;
    private javax.swing.JLabel lbl_StreetHouse;
    private javax.swing.JLabel lbl_Username;
    private javax.swing.JLabel lbl_ZIP;
    private javax.swing.JTextField tf_City;
    private javax.swing.JTextField tf_FirstName;
    private javax.swing.JTextField tf_LastName;
    private javax.swing.JTextField tf_Mail;
    private javax.swing.JTextField tf_Password;
    private javax.swing.JTextField tf_PhoneNumber;
    private javax.swing.JTextField tf_RepeatMail;
    private javax.swing.JTextField tf_RepeatPassword;
    private javax.swing.JTextField tf_StreetHouse;
    private javax.swing.JTextField tf_Username;
    private javax.swing.JTextField tf_ZIP;
    // End of variables declaration//GEN-END:variables
}
