/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MedicationOrderSystem.Forms;

/**
 *
 * @author OENAL
 */
public class UserGUI extends javax.swing.JFrame {

    /**
     * Creates new form UserGUI
     */
    public UserGUI() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        leftSide = new javax.swing.JPanel();
        ls_btn_LogOut = new javax.swing.JButton();
        ls_btn_Home = new javax.swing.JButton();
        ls_btn_Settings = new javax.swing.JButton();
        ls_btn_NewOrderPrescription = new javax.swing.JButton();
        ls_btn_NewOrderOTC = new javax.swing.JButton();
        ls_btn_1 = new javax.swing.JButton();
        ls_btn_2 = new javax.swing.JButton();
        rightSide = new javax.swing.JPanel();
        homePage = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        settingsPage = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lastNameTxt = new javax.swing.JTextField();
        firstNameTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        mailTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        genderBx = new javax.swing.JComboBox<>();
        streetTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        zipTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cityTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        oldPswrdTxt = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        newPswrdTxt = new javax.swing.JPasswordField();
        repeatPaswrdTxt = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        sp_btn_DeleteAccount = new javax.swing.JButton();
        newOrderPrescription = new javax.swing.JPanel();
        nor_lbl_NewOrder = new javax.swing.JLabel();
        nor_lbl_HI = new javax.swing.JLabel();
        nor_tf_HI = new javax.swing.JTextField();
        nor_btn_OrderNow = new javax.swing.JButton();
        nor_lbl_INum = new javax.swing.JLabel();
        nor_tf_INum = new javax.swing.JTextField();
        nor_tf_BusLocNum = new javax.swing.JTextField();
        nor_lbl_BusLocNum = new javax.swing.JLabel();
        nor_lbl_Med2 = new javax.swing.JLabel();
        nor_tf_Med2 = new javax.swing.JTextField();
        nor_tf_DocNum = new javax.swing.JTextField();
        nor_lbl_DocNum = new javax.swing.JLabel();
        nor_tf_Med1 = new javax.swing.JTextField();
        nor_lbl_Med1 = new javax.swing.JLabel();
        nor_tf_HINum = new javax.swing.JTextField();
        nor_lbl_HINum = new javax.swing.JLabel();
        nor_btn_AddDelMed = new javax.swing.JButton();
        nor_tf_Med3 = new javax.swing.JTextField();
        nor_lbl_Med3 = new javax.swing.JLabel();
        nor_tf_Med4 = new javax.swing.JTextField();
        nor_lbl_Med4 = new javax.swing.JLabel();
        nor_tf_Med5 = new javax.swing.JTextField();
        nor_lbl_Med5 = new javax.swing.JLabel();
        nor_jdc_PresDate = new com.toedter.calendar.JDateChooser();
        nor_lbl_PresDate = new javax.swing.JLabel();
        newOrderOTC = new javax.swing.JPanel();
        notc_lbl_NewOrder = new javax.swing.JLabel();
        notc_btn_OrderNow = new javax.swing.JButton();
        notc_lbl_Med1 = new javax.swing.JLabel();
        notc_tf_Med1 = new javax.swing.JTextField();
        notc_lbl_Med2 = new javax.swing.JLabel();
        notc_tf_Med2 = new javax.swing.JTextField();
        notc_lbl_Notes = new javax.swing.JLabel();
        notc_tf_Notes = new javax.swing.JTextField();
        notc_lbl_Med3 = new javax.swing.JLabel();
        notc_tf_Med3 = new javax.swing.JTextField();
        clickedOrderNow = new javax.swing.JPanel();
        con_lbl_Text = new javax.swing.JLabel();
        con_lbl_CON = new javax.swing.JLabel();
        con_lbl_Done = new javax.swing.JButton();
        deleteAccountClicked = new javax.swing.JPanel();
        dac_lbl_DelAcc = new javax.swing.JLabel();
        dac_lbl_Text = new javax.swing.JLabel();
        dac_lbl_Done = new javax.swing.JButton();
        dac_lbl_Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        topPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MOSLogoKlein.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MOS.DE");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18))
        );

        leftSide.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ls_btn_LogOut.setText("LogOut");
        ls_btn_LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ls_btn_LogOutActionPerformed(evt);
            }
        });

        ls_btn_Home.setText("Home");
        ls_btn_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ls_btn_HomeActionPerformed(evt);
            }
        });

        ls_btn_Settings.setText("Settings");
        ls_btn_Settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ls_btn_SettingsActionPerformed(evt);
            }
        });

        ls_btn_NewOrderPrescription.setText("<html>\n<p align = \"center\">New Order<br>Prescription</p>\n<html/>");
        ls_btn_NewOrderPrescription.setToolTipText("");
        ls_btn_NewOrderPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ls_btn_NewOrderPrescriptionActionPerformed(evt);
            }
        });

        ls_btn_NewOrderOTC.setText("<html>\n<p align = \"center\">New Order<br>OTC</p>\n\n\n<html/>");
        ls_btn_NewOrderOTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ls_btn_NewOrderOTCActionPerformed(evt);
            }
        });

        ls_btn_1.setText("1");

        ls_btn_2.setText("2");

        javax.swing.GroupLayout leftSideLayout = new javax.swing.GroupLayout(leftSide);
        leftSide.setLayout(leftSideLayout);
        leftSideLayout.setHorizontalGroup(
            leftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ls_btn_LogOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ls_btn_Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ls_btn_Settings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ls_btn_NewOrderPrescription, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ls_btn_NewOrderOTC, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ls_btn_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ls_btn_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        leftSideLayout.setVerticalGroup(
            leftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftSideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ls_btn_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ls_btn_Settings, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ls_btn_NewOrderPrescription, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ls_btn_NewOrderOTC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ls_btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ls_btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ls_btn_LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        rightSide.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rightSide.setLayout(new java.awt.CardLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Hello User!");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Your Orders:");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout homePageLayout = new javax.swing.GroupLayout(homePage);
        homePage.setLayout(homePageLayout);
        homePageLayout.setHorizontalGroup(
            homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE))
                .addContainerGap())
        );
        homePageLayout.setVerticalGroup(
            homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightSide.add(homePage, "card2");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Settings:");

        jLabel6.setText("FirstName:");

        firstNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTxtActionPerformed(evt);
            }
        });

        jLabel7.setText("Lastname:");

        jLabel8.setText("Mail:");

        jLabel9.setText("Gender:");

        genderBx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setText("Street:");

        jLabel11.setText("ZIP:");

        jLabel12.setText("City:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("Password reset:");

        jLabel14.setText("Old password:");

        jLabel15.setText("New password:");

        jLabel16.setText("Repeat password:");

        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");

        resetBtn.setText("Reset");

        saveBtn.setText("Save");

        sp_btn_DeleteAccount.setForeground(new java.awt.Color(255, 0, 0));
        sp_btn_DeleteAccount.setText("Delete Account");
        sp_btn_DeleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sp_btn_DeleteAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout settingsPageLayout = new javax.swing.GroupLayout(settingsPage);
        settingsPage.setLayout(settingsPageLayout);
        settingsPageLayout.setHorizontalGroup(
            settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsPageLayout.createSequentialGroup()
                        .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, settingsPageLayout.createSequentialGroup()
                                .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(settingsPageLayout.createSequentialGroup()
                                        .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(genderBx, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel11))
                                .addGap(0, 89, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(settingsPageLayout.createSequentialGroup()
                        .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(settingsPageLayout.createSequentialGroup()
                                .addComponent(streetTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(zipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(settingsPageLayout.createSequentialGroup()
                                .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(oldPswrdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newPswrdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(repeatPaswrdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(settingsPageLayout.createSequentialGroup()
                                .addComponent(editBtn)
                                .addGap(18, 18, 18)
                                .addComponent(cancelBtn)
                                .addGap(18, 18, 18)
                                .addComponent(saveBtn))
                            .addComponent(resetBtn))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sp_btn_DeleteAccount)
                .addContainerGap())
        );
        settingsPageLayout.setVerticalGroup(
            settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(genderBx))
                .addGap(18, 18, 18)
                .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(streetTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editBtn)
                    .addComponent(cancelBtn)
                    .addComponent(saveBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldPswrdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPswrdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repeatPaswrdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resetBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(sp_btn_DeleteAccount)
                .addContainerGap())
        );

        rightSide.add(settingsPage, "card3");

        nor_lbl_NewOrder.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nor_lbl_NewOrder.setText("New Order (With Prescription):");

        nor_lbl_HI.setText("Health Insurance:");

        nor_tf_HI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nor_tf_HIActionPerformed(evt);
            }
        });

        nor_btn_OrderNow.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nor_btn_OrderNow.setText("Order Now");
        nor_btn_OrderNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nor_btn_OrderNowActionPerformed(evt);
            }
        });

        nor_lbl_INum.setText("Insurance Number:");

        nor_tf_INum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nor_tf_INumActionPerformed(evt);
            }
        });

        nor_tf_BusLocNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nor_tf_BusLocNumActionPerformed(evt);
            }
        });

        nor_lbl_BusLocNum.setText("Business Location Number:");

        nor_lbl_Med2.setText("Medication 2:");

        nor_tf_Med2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nor_tf_Med2ActionPerformed(evt);
            }
        });

        nor_tf_DocNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nor_tf_DocNumActionPerformed(evt);
            }
        });

        nor_lbl_DocNum.setText("Doctor Number:");

        nor_tf_Med1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nor_tf_Med1ActionPerformed(evt);
            }
        });

        nor_lbl_Med1.setText("Medication:");

        nor_tf_HINum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nor_tf_HINumActionPerformed(evt);
            }
        });

        nor_lbl_HINum.setText("Health Insurance Number:");

        nor_btn_AddDelMed.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        nor_btn_AddDelMed.setText("+");
        nor_btn_AddDelMed.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nor_btn_AddDelMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nor_btn_AddDelMedActionPerformed(evt);
            }
        });

        nor_tf_Med3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nor_tf_Med3ActionPerformed(evt);
            }
        });

        nor_lbl_Med3.setText("Medication 3:");

        nor_tf_Med4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nor_tf_Med4ActionPerformed(evt);
            }
        });

        nor_lbl_Med4.setText("Medication 4:");

        nor_tf_Med5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nor_tf_Med5ActionPerformed(evt);
            }
        });

        nor_lbl_Med5.setText("Medication 5:");

        nor_lbl_PresDate.setText("Prescription Date: ");

        javax.swing.GroupLayout newOrderPrescriptionLayout = new javax.swing.GroupLayout(newOrderPrescription);
        newOrderPrescription.setLayout(newOrderPrescriptionLayout);
        newOrderPrescriptionLayout.setHorizontalGroup(
            newOrderPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newOrderPrescriptionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newOrderPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newOrderPrescriptionLayout.createSequentialGroup()
                        .addGroup(newOrderPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newOrderPrescriptionLayout.createSequentialGroup()
                                .addGroup(newOrderPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nor_lbl_HI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nor_tf_HI)
                                    .addComponent(nor_lbl_BusLocNum, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(nor_tf_BusLocNum, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(nor_lbl_PresDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nor_jdc_PresDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(newOrderPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nor_lbl_Med2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(newOrderPrescriptionLayout.createSequentialGroup()
                                        .addComponent(nor_tf_Med2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(nor_btn_AddDelMed))
                                    .addGroup(newOrderPrescriptionLayout.createSequentialGroup()
                                        .addGroup(newOrderPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nor_lbl_HINum, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nor_tf_HINum, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(newOrderPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nor_lbl_Med3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nor_tf_Med3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(newOrderPrescriptionLayout.createSequentialGroup()
                                        .addGroup(newOrderPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nor_lbl_Med1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nor_tf_Med1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(newOrderPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nor_lbl_Med5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nor_tf_Med5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(nor_btn_OrderNow, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(newOrderPrescriptionLayout.createSequentialGroup()
                                .addGroup(newOrderPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nor_lbl_INum, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nor_tf_INum, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(newOrderPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nor_lbl_DocNum, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nor_tf_DocNum, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(newOrderPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nor_lbl_Med4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nor_tf_Med4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(nor_lbl_NewOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        newOrderPrescriptionLayout.setVerticalGroup(
            newOrderPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newOrderPrescriptionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nor_lbl_NewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newOrderPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(newOrderPrescriptionLayout.createSequentialGroup()
                        .addComponent(nor_lbl_HI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nor_tf_HI, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nor_lbl_INum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nor_tf_INum, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newOrderPrescriptionLayout.createSequentialGroup()
                        .addGroup(newOrderPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newOrderPrescriptionLayout.createSequentialGroup()
                                .addComponent(nor_lbl_HINum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nor_tf_HINum, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(newOrderPrescriptionLayout.createSequentialGroup()
                                .addComponent(nor_lbl_Med3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nor_tf_Med3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(newOrderPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newOrderPrescriptionLayout.createSequentialGroup()
                                .addComponent(nor_lbl_DocNum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nor_tf_DocNum, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(newOrderPrescriptionLayout.createSequentialGroup()
                                .addComponent(nor_lbl_Med4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nor_tf_Med4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(newOrderPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newOrderPrescriptionLayout.createSequentialGroup()
                        .addComponent(nor_lbl_BusLocNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nor_tf_BusLocNum, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newOrderPrescriptionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(newOrderPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newOrderPrescriptionLayout.createSequentialGroup()
                                .addComponent(nor_lbl_Med1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nor_tf_Med1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newOrderPrescriptionLayout.createSequentialGroup()
                                .addComponent(nor_lbl_Med5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nor_tf_Med5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(newOrderPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nor_lbl_Med2)
                    .addComponent(nor_lbl_PresDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newOrderPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newOrderPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nor_btn_AddDelMed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nor_tf_Med2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                    .addComponent(nor_jdc_PresDate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(nor_btn_OrderNow, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        rightSide.add(newOrderPrescription, "card4");

        notc_lbl_NewOrder.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        notc_lbl_NewOrder.setText("New Order Over The Counter (No Prescription):");

        notc_btn_OrderNow.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        notc_btn_OrderNow.setText("Order Now");
        notc_btn_OrderNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notc_btn_OrderNowActionPerformed(evt);
            }
        });

        notc_lbl_Med1.setText("Medication:");

        notc_tf_Med1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notc_tf_Med1ActionPerformed(evt);
            }
        });

        notc_lbl_Med2.setText("Medication 2:");

        notc_tf_Med2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notc_tf_Med2ActionPerformed(evt);
            }
        });

        notc_lbl_Notes.setText("Notes:");

        notc_tf_Notes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notc_tf_NotesActionPerformed(evt);
            }
        });

        notc_lbl_Med3.setText("Medication 3:");

        notc_tf_Med3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notc_tf_Med3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newOrderOTCLayout = new javax.swing.GroupLayout(newOrderOTC);
        newOrderOTC.setLayout(newOrderOTCLayout);
        newOrderOTCLayout.setHorizontalGroup(
            newOrderOTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newOrderOTCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newOrderOTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notc_lbl_NewOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                    .addGroup(newOrderOTCLayout.createSequentialGroup()
                        .addGroup(newOrderOTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newOrderOTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(notc_tf_Med1)
                                .addComponent(notc_lbl_Med1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(notc_lbl_Med2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(notc_tf_Med2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(notc_lbl_Med3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(notc_tf_Med3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(newOrderOTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notc_lbl_Notes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(notc_tf_Notes))))
                .addContainerGap())
            .addGroup(newOrderOTCLayout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(notc_btn_OrderNow, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        newOrderOTCLayout.setVerticalGroup(
            newOrderOTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newOrderOTCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(notc_lbl_NewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(newOrderOTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notc_lbl_Med1)
                    .addComponent(notc_lbl_Notes))
                .addGap(18, 18, 18)
                .addGroup(newOrderOTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(newOrderOTCLayout.createSequentialGroup()
                        .addComponent(notc_tf_Med1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(notc_lbl_Med2)
                        .addGap(18, 18, 18)
                        .addComponent(notc_tf_Med2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(notc_lbl_Med3)
                        .addGap(18, 18, 18)
                        .addComponent(notc_tf_Med3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(notc_tf_Notes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(notc_btn_OrderNow, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        rightSide.add(newOrderOTC, "card5");

        con_lbl_Text.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        con_lbl_Text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        con_lbl_Text.setText("<html> <p align = \"center\">You can look up your <b>Orders</b> by going to the <b>Home</b> tab and selecting the <b>Orders</b>.</p> <p align = \"center\"; style=\"color:#33FFFF\">Please ensure you bring your <b>prescription</b> and valid form of <b>identification</b> when you come to pick up your order.</p> <p align = \"center\">Thank <b>YOU</b> for choosing us.</p> </html>");

        con_lbl_CON.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        con_lbl_CON.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        con_lbl_CON.setText("Your order has been successfully placed!");

        con_lbl_Done.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        con_lbl_Done.setText("Done");
        con_lbl_Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_lbl_DoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clickedOrderNowLayout = new javax.swing.GroupLayout(clickedOrderNow);
        clickedOrderNow.setLayout(clickedOrderNowLayout);
        clickedOrderNowLayout.setHorizontalGroup(
            clickedOrderNowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clickedOrderNowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clickedOrderNowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(con_lbl_CON, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                    .addComponent(con_lbl_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(clickedOrderNowLayout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(con_lbl_Done, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        clickedOrderNowLayout.setVerticalGroup(
            clickedOrderNowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clickedOrderNowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(con_lbl_CON, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(con_lbl_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(con_lbl_Done, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        rightSide.add(clickedOrderNow, "card6");

        dac_lbl_DelAcc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dac_lbl_DelAcc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dac_lbl_DelAcc.setText("Do you want to delete your account?");

        dac_lbl_Text.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dac_lbl_Text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dac_lbl_Text.setText("<html>\n<p align = \"center\">Do you really want to leave us?.</p>\n<p align = \"center\"; style = color:red\">You will not be able to order medications or use this platform without an account.</p>\n<p align = \"center\"; style =\"color:red\">You can recover your account later if you want to come back to us.</p> \n<p align = \"center\">We wish you the best for your future!</p>\n</html>");

        dac_lbl_Done.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dac_lbl_Done.setForeground(new java.awt.Color(255, 51, 51));
        dac_lbl_Done.setText("Delete Account");
        dac_lbl_Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dac_lbl_DoneActionPerformed(evt);
            }
        });

        dac_lbl_Back.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dac_lbl_Back.setText("Go Back");
        dac_lbl_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dac_lbl_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deleteAccountClickedLayout = new javax.swing.GroupLayout(deleteAccountClicked);
        deleteAccountClicked.setLayout(deleteAccountClickedLayout);
        deleteAccountClickedLayout.setHorizontalGroup(
            deleteAccountClickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteAccountClickedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteAccountClickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dac_lbl_DelAcc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                    .addComponent(dac_lbl_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(deleteAccountClickedLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addGroup(deleteAccountClickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dac_lbl_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dac_lbl_Done, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deleteAccountClickedLayout.setVerticalGroup(
            deleteAccountClickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteAccountClickedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dac_lbl_DelAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(dac_lbl_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dac_lbl_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(dac_lbl_Done, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        rightSide.add(deleteAccountClicked, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(leftSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rightSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leftSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ls_btn_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ls_btn_HomeActionPerformed
        // TODO add your handling code here:
        rightSide.removeAll();
        rightSide.add(homePage);
        rightSide.repaint();
        rightSide.revalidate();
    }//GEN-LAST:event_ls_btn_HomeActionPerformed

    private void ls_btn_SettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ls_btn_SettingsActionPerformed
        // TODO add your handling code here:
        rightSide.removeAll();
        rightSide.add(settingsPage);
        rightSide.repaint();
        rightSide.revalidate();
    }//GEN-LAST:event_ls_btn_SettingsActionPerformed

    private void ls_btn_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ls_btn_LogOutActionPerformed
        // TODO add your handling code here:
        new LoginGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_ls_btn_LogOutActionPerformed

    private void firstNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTxtActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBtnActionPerformed

    private void nor_tf_HIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nor_tf_HIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nor_tf_HIActionPerformed

    private void nor_btn_OrderNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nor_btn_OrderNowActionPerformed
        rightSide.removeAll();
        rightSide.add(clickedOrderNow);
        rightSide.repaint();
        rightSide.revalidate();
    }//GEN-LAST:event_nor_btn_OrderNowActionPerformed

    private void nor_tf_INumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nor_tf_INumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nor_tf_INumActionPerformed

    private void nor_tf_BusLocNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nor_tf_BusLocNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nor_tf_BusLocNumActionPerformed

    private void nor_tf_Med2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nor_tf_Med2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nor_tf_Med2ActionPerformed

    private void nor_tf_DocNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nor_tf_DocNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nor_tf_DocNumActionPerformed

    private void nor_tf_Med1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nor_tf_Med1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nor_tf_Med1ActionPerformed

    private void nor_tf_HINumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nor_tf_HINumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nor_tf_HINumActionPerformed

    private void nor_btn_AddDelMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nor_btn_AddDelMedActionPerformed
        if(nor_btn_AddDelMed.getText() == "+"){
            
            nor_lbl_Med3.setVisible(true);
            nor_lbl_Med4.setVisible(true);
            nor_lbl_Med5.setVisible(true);
            
            nor_tf_Med3.setVisible(true);
            nor_tf_Med4.setVisible(true);
            nor_tf_Med5.setVisible(true);

            System.out.println("AddDel == +");
            
            nor_btn_AddDelMed.setText("-");
        }
        else if(nor_btn_AddDelMed.getText() == "-"){
            
            nor_lbl_Med3.setVisible(false);
            nor_lbl_Med4.setVisible(false);
            nor_lbl_Med5.setVisible(false);
            
            nor_tf_Med3.setVisible(false);
            nor_tf_Med4.setVisible(false);
            nor_tf_Med5.setVisible(false);

            System.out.println("AddDel == -");
            
            nor_btn_AddDelMed.setText("+");
        }
    }//GEN-LAST:event_nor_btn_AddDelMedActionPerformed

    private void nor_tf_Med3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nor_tf_Med3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nor_tf_Med3ActionPerformed

    private void nor_tf_Med4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nor_tf_Med4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nor_tf_Med4ActionPerformed

    private void nor_tf_Med5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nor_tf_Med5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nor_tf_Med5ActionPerformed

    private void ls_btn_NewOrderPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ls_btn_NewOrderPrescriptionActionPerformed
        rightSide.removeAll();
        rightSide.add(newOrderPrescription);
        rightSide.repaint();
        rightSide.revalidate(); 
        
        nor_lbl_Med3.setVisible(false);
        nor_lbl_Med4.setVisible(false);
        nor_lbl_Med5.setVisible(false);

        nor_tf_Med3.setVisible(false);
        nor_tf_Med4.setVisible(false);
        nor_tf_Med5.setVisible(false);
    }//GEN-LAST:event_ls_btn_NewOrderPrescriptionActionPerformed

    private void notc_btn_OrderNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notc_btn_OrderNowActionPerformed
        rightSide.removeAll();
        rightSide.add(clickedOrderNow);
        rightSide.repaint();
        rightSide.revalidate();
    }//GEN-LAST:event_notc_btn_OrderNowActionPerformed

    private void notc_tf_Med1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notc_tf_Med1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notc_tf_Med1ActionPerformed

    private void notc_tf_Med2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notc_tf_Med2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notc_tf_Med2ActionPerformed

    private void notc_tf_NotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notc_tf_NotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notc_tf_NotesActionPerformed

    private void notc_tf_Med3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notc_tf_Med3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notc_tf_Med3ActionPerformed

    private void ls_btn_NewOrderOTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ls_btn_NewOrderOTCActionPerformed
        rightSide.removeAll();
        rightSide.add(newOrderOTC);
        rightSide.repaint();
        rightSide.revalidate();       
        
    }//GEN-LAST:event_ls_btn_NewOrderOTCActionPerformed

    private void sp_btn_DeleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sp_btn_DeleteAccountActionPerformed
        rightSide.removeAll();
        rightSide.add(deleteAccountClicked);
        rightSide.repaint();
        rightSide.revalidate();
    }//GEN-LAST:event_sp_btn_DeleteAccountActionPerformed

    private void con_lbl_DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_lbl_DoneActionPerformed
        rightSide.removeAll();
        rightSide.add(homePage);
        rightSide.repaint();
        rightSide.revalidate();
    }//GEN-LAST:event_con_lbl_DoneActionPerformed

    private void dac_lbl_DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dac_lbl_DoneActionPerformed
        System.exit(0);
    }//GEN-LAST:event_dac_lbl_DoneActionPerformed

    private void dac_lbl_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dac_lbl_BackActionPerformed
        rightSide.removeAll();
        rightSide.add(settingsPage);
        rightSide.repaint();
        rightSide.revalidate();
    }//GEN-LAST:event_dac_lbl_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JPanel clickedOrderNow;
    private javax.swing.JLabel con_lbl_CON;
    private javax.swing.JButton con_lbl_Done;
    private javax.swing.JLabel con_lbl_Text;
    private javax.swing.JButton dac_lbl_Back;
    private javax.swing.JLabel dac_lbl_DelAcc;
    private javax.swing.JButton dac_lbl_Done;
    private javax.swing.JLabel dac_lbl_Text;
    private javax.swing.JPanel deleteAccountClicked;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField firstNameTxt;
    private javax.swing.JComboBox<String> genderBx;
    private javax.swing.JPanel homePage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JPanel leftSide;
    private javax.swing.JButton ls_btn_1;
    private javax.swing.JButton ls_btn_2;
    private javax.swing.JButton ls_btn_Home;
    private javax.swing.JButton ls_btn_LogOut;
    private javax.swing.JButton ls_btn_NewOrderOTC;
    private javax.swing.JButton ls_btn_NewOrderPrescription;
    private javax.swing.JButton ls_btn_Settings;
    private javax.swing.JTextField mailTxt;
    private javax.swing.JPanel newOrderOTC;
    private javax.swing.JPanel newOrderPrescription;
    private javax.swing.JPasswordField newPswrdTxt;
    private javax.swing.JButton nor_btn_AddDelMed;
    private javax.swing.JButton nor_btn_OrderNow;
    private com.toedter.calendar.JDateChooser nor_jdc_PresDate;
    private javax.swing.JLabel nor_lbl_BusLocNum;
    private javax.swing.JLabel nor_lbl_DocNum;
    private javax.swing.JLabel nor_lbl_HI;
    private javax.swing.JLabel nor_lbl_HINum;
    private javax.swing.JLabel nor_lbl_INum;
    private javax.swing.JLabel nor_lbl_Med1;
    private javax.swing.JLabel nor_lbl_Med2;
    private javax.swing.JLabel nor_lbl_Med3;
    private javax.swing.JLabel nor_lbl_Med4;
    private javax.swing.JLabel nor_lbl_Med5;
    private javax.swing.JLabel nor_lbl_NewOrder;
    private javax.swing.JLabel nor_lbl_PresDate;
    private javax.swing.JTextField nor_tf_BusLocNum;
    private javax.swing.JTextField nor_tf_DocNum;
    private javax.swing.JTextField nor_tf_HI;
    private javax.swing.JTextField nor_tf_HINum;
    private javax.swing.JTextField nor_tf_INum;
    private javax.swing.JTextField nor_tf_Med1;
    private javax.swing.JTextField nor_tf_Med2;
    private javax.swing.JTextField nor_tf_Med3;
    private javax.swing.JTextField nor_tf_Med4;
    private javax.swing.JTextField nor_tf_Med5;
    private javax.swing.JButton notc_btn_OrderNow;
    private javax.swing.JLabel notc_lbl_Med1;
    private javax.swing.JLabel notc_lbl_Med2;
    private javax.swing.JLabel notc_lbl_Med3;
    private javax.swing.JLabel notc_lbl_NewOrder;
    private javax.swing.JLabel notc_lbl_Notes;
    private javax.swing.JTextField notc_tf_Med1;
    private javax.swing.JTextField notc_tf_Med2;
    private javax.swing.JTextField notc_tf_Med3;
    private javax.swing.JTextField notc_tf_Notes;
    private javax.swing.JPasswordField oldPswrdTxt;
    private javax.swing.JPasswordField repeatPaswrdTxt;
    private javax.swing.JButton resetBtn;
    private javax.swing.JPanel rightSide;
    private javax.swing.JButton saveBtn;
    private javax.swing.JPanel settingsPage;
    private javax.swing.JButton sp_btn_DeleteAccount;
    private javax.swing.JTextField streetTxt;
    private javax.swing.JPanel topPanel;
    private javax.swing.JTextField zipTxt;
    // End of variables declaration//GEN-END:variables
}
