/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MedicationOrderSystem;


import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import javax.swing.JTextField;
/**
 *
 * @author OENAL
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        addPlaceholderStyle(LoginUsernameFld);
        addPlaceholderStyle(LoginPasswordFld);
    }
    
    public void addPlaceholderStyle(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.gray);
    }
    
    public void removePlaceholderStyle(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN|Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LoginUsernameFld = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        LoginPasswordFld = new javax.swing.JPasswordField();
        LoginRegistrationBtn = new javax.swing.JButton();
        LoginPasswordResetBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MOS System");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("MOS System");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 35, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oenal\\OneDrive - HBK\\Documents\\ProgEx\\MedicationOrderSystem-master\\src\\main\\java\\MedicationOrderSystem\\icons\\MOSLogo.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 95, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oenal\\OneDrive - HBK\\Documents\\ProgEx\\MedicationOrderSystem-master\\src\\main\\java\\MedicationOrderSystem\\icons\\password.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        LoginUsernameFld.setText("Username");
        LoginUsernameFld.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LoginUsernameFldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LoginUsernameFldFocusLost(evt);
            }
        });
        LoginUsernameFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginUsernameFldKeyPressed(evt);
            }
        });
        getContentPane().add(LoginUsernameFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 219, 37));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oenal\\OneDrive - HBK\\Documents\\ProgEx\\MedicationOrderSystem-master\\src\\main\\java\\MedicationOrderSystem\\icons\\username.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        LoginPasswordFld.setText("Password");
        LoginPasswordFld.setEchoChar('\u0000');
        LoginPasswordFld.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LoginPasswordFldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LoginPasswordFldFocusLost(evt);
            }
        });
        LoginPasswordFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginPasswordFldKeyPressed(evt);
            }
        });
        getContentPane().add(LoginPasswordFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 219, 37));

        LoginRegistrationBtn.setText("Registration");
        LoginRegistrationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginRegistrationBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LoginRegistrationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, -1, -1));

        LoginPasswordResetBtn.setText("Password reset");
        getContentPane().add(LoginPasswordResetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 590, -1, -1));

        LoginLoginbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oenal\\OneDrive - HBK\\Documents\\ProgEx\\MedicationOrderSystem-master\\src\\main\\java\\MedicationOrderSystem\\icons\\login.png")); // NOI18N
        LoginLoginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginLoginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(LoginLoginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 50, 50));

        jLabel5.setToolTipText("");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 350, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginRegistrationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginRegistrationBtnActionPerformed
        // TODO add your handling code here:
        new Registration().setVisible(true);
    }//GEN-LAST:event_LoginRegistrationBtnActionPerformed

    private void LoginUsernameFldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LoginUsernameFldFocusGained
        // TODO add your handling code here:
        if(LoginUsernameFld.getText().equals("Username")){
            LoginUsernameFld.setText(null);
            LoginUsernameFld.requestFocus();
            removePlaceholderStyle(LoginUsernameFld);
        }
    }//GEN-LAST:event_LoginUsernameFldFocusGained

    private void LoginPasswordFldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LoginPasswordFldFocusGained
        // TODO add your handling code here:
        if(LoginPasswordFld.getText().equals("Password")){
            LoginPasswordFld.setText(null);
            LoginPasswordFld.requestFocus();
            LoginPasswordFld.setEchoChar('\u2022');
            removePlaceholderStyle(LoginPasswordFld);
        }
    }//GEN-LAST:event_LoginPasswordFldFocusGained

    private void LoginUsernameFldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LoginUsernameFldFocusLost
        // TODO add your handling code here:
        if(LoginUsernameFld.getText().length()==0){
            addPlaceholderStyle(LoginUsernameFld);
            LoginUsernameFld.setText("Username");
        }
    }//GEN-LAST:event_LoginUsernameFldFocusLost

    private void LoginPasswordFldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LoginPasswordFldFocusLost
        // TODO add your handling code here:
        if(LoginPasswordFld.getText().length()==0){
            addPlaceholderStyle(LoginPasswordFld);
            LoginPasswordFld.setText("Password");
            LoginPasswordFld.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_LoginPasswordFldFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void LoginPasswordFldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginPasswordFldKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        
        if(key == KeyEvent.VK_ENTER){
            LoginLoginbtn.doClick();
        }
    }//GEN-LAST:event_LoginPasswordFldKeyPressed

    private void LoginLoginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginLoginbtnActionPerformed
        // TODO add your handling code here:
        new User().setVisible(true);
        dispose();
    }//GEN-LAST:event_LoginLoginbtnActionPerformed

    private void LoginUsernameFldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginUsernameFldKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        
        if(key == KeyEvent.VK_ENTER){
            LoginLoginbtn.doClick();
        }
    }//GEN-LAST:event_LoginUsernameFldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final javax.swing.JButton LoginLoginbtn = new javax.swing.JButton();
    private javax.swing.JPasswordField LoginPasswordFld;
    private javax.swing.JButton LoginPasswordResetBtn;
    private javax.swing.JButton LoginRegistrationBtn;
    private javax.swing.JTextField LoginUsernameFld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

}
